<?php

namespace Models\Lists;

use Models\AbstractIblockPropertyValuesTable;
use Bitrix\Main\Entity\ReferenceField;

class CarsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 18;

    public static function getMap(): array
    {
        $map = [
            'CITY' => new ReferenceField(
                'CITY',
                CarCityPropertyValuesTable::class, 
                ['=this.CITY_ID' => 'ref.IBLOCK_ELEMENT_ID']
            )
        ];

        return parent::getMap() + $map; // TODO: Change the autogenerated stub

    }
}
