<?php

namespace Models\Lists;

use Bitrix\Main\ORM\Query\Join;
use Models\AbstractIblockPropertyValuesTable;
use Bitrix\Main\Entity\ReferenceField;


//class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
//{
//    public const IBLOCK_ID = 16;

//    public static function getMap(): array
//    {
//        $map = [
//            'PROCEDURES_INFO' => new ReferenceField(
//                'PROCEDURES_INFO',
//                DoctorsProcPropertyValuesTable::class,
//                ['=this.PROC_IDS_MULTI' => 'ref.IBLOCK_ELEMENT_ID'],
//            )
//        ];
//
//        return parent::getMap() + $map; // TODO: Change the autogenerated stub
//    }

//}

class DoctorsPropertyValuesTable extends AbstractIblockPropertyValuesTable
{
    public const IBLOCK_ID = 16;

//    public static function getMap(): array
//    {
//        $map = [
//            'PROCEDURES_INFO' => new Reference(
//                'PROCEDURES_INFO',
//                DoctorsProcPropertyValuesTable::class,
//                Join::on('this.PROC_IDS_MULTI', 'ref.IBLOCK_ELEMENT_ID')
//                    ->whereExpr('FIND_IN_SET(ref.IBLOCK_ELEMENT_ID, this.PROC_IDS_MULTI) > 0')
//            )
//        ];
//
//        return parent::getMap() + $map;
//    }
}
